apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: taskrun-transceiver
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/triggermesh/aktion/cmd/transceiver
            env:
              - name: TASK_NAME
                value: "hello"
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
